language: python
sudo: false
branches:
  only:
    - master
git:
  submodules: false
before_install:
    - git submodule update --init --recursive
install: "pip install -r requirements.txt"
script: 
    - pelican content
    - fab publish
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
