language: python
sudo: false
git:
  submodules: false
before_install:
    - git submodule update --init --recursive
    - echo -e "Host 162.243.186.254\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - openssl aes-256-cbc -K $encrypted_bd9d366e80a4_key -iv $encrypted_bd9d366e80a4_iv -in deploy-key.enc -out deploy-key -d
    - chmod 600 deploy-key
    - mv deploy-key ~/.ssh/id_rsa
install: "pip install -r requirements.txt"
script: 
    - pelican content
    - fab publish
