language: python
sudo: false
branches:
  only:
    - master
git:
  submodules: false
before_install:
    - git submodule update --init --recursive
install: "pip install -r requirements.txt"
script: 
    - pelican content
    - fab publish
