baseURL = "https://www.maugzoide.com/"
defaultContentLanguage = "en"
title = "Mauricio Antunes"
paginate = 3
theme = "jane"
disqusShortname = "maugzoide"

[author] 
    name = "Maurício Antunes"

[sitemap]
    changefreq = "weekly"
    priority = 0.5
    filename = "sitemap.xml"

[[menu.main]]
    name = "Home"
    weight = 10
    identifier = "home"
    url = "/"

[params]
    title = "hello people"
    description = "people, technology, culture"
    since = "2015"
    moreMeta = true

[params.social]
    a-github = "https://github.com/mauricioabreu"
    b-twitter = "https://twitter.com/maugzoide"
    c-email = "mailto:mauricio.abreua@gmail.com"
    